import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-200 p-10">
          <Navbar />
          {children}
          <span className="flex justify-center text-gray-500 mt-10">
            &copy; {new Date().getFullYear()} Ariq Daffa.
          </span>
        </div>
      </body>
    </html>
  );
}
