import type { Metadata } from "next";
import { Poppins, Work_Sans } from "next/font/google";
import "./globals.css";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: '500',
  subsets: ['latin'],
  variable: '--font-poppins',
})

const poppinsBold = Poppins({
  weight: '800',
  subsets: ['latin'],
  variable: '--font-poppins-bold',
})

export const metadata: Metadata = {
  title: "Ariq's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${poppins.variable} ${poppinsBold.variable} antialiased`}
      >
        <div className="min-h-screen p-10">
          {children}
          <span className="flex justify-center text-gray-500 mt-10">
            &copy; {new Date().getFullYear()} Ariq Daffa.
          </span>
        </div>
      </body>
    </html>
  );
}
