import type { Metadata } from "next";
import { Poppins, Work_Sans } from "next/font/google";
import "./globals.css";
import ScrollToTopButton from "@/components/ScrollToTop";
import { PostHogProvider } from '../providers/posthog'
import { GoogleAnalytics } from '@next/third-parties/google'

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: '500',
  subsets: ['latin'],
  variable: '--font-poppins',
})

const poppinsBold = Poppins({
  weight: '800',
  subsets: ['latin'],
  variable: '--font-poppins-bold',
})

export const metadata: Metadata = {
  title: "Ariq's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${poppins.variable} ${poppinsBold.variable} antialiased`}
      >
        <PostHogProvider>
          <div className="bg-[url('/gradient-bg.jpg')] bg-fixed bg-cover">
            {children}
            <ScrollToTopButton />
            <span className="flex justify-center text-gray-500 py-10 bg-white">
              &copy; {new Date().getFullYear()} Ariq Daffa Athallah Putra
            </span>
          </div>
        </PostHogProvider>
        {process.env.GOOGLE_ANALYTICS_KEY && <GoogleAnalytics gaId={process.env.GOOGLE_ANALYTICS_KEY} />}
      </body>
    </html>
  );
}
